### ISSUE TITLE
Restore wallet from privatekey

### ISSUE THREAD

**Issue by Elektryon-Dev** [ombre-projects/ombre#19]
When you try to restore a wallet using ombre-wallet-cli binaries it will give a save error due to the filename of the new wallet beeing too long. It tries to save the new wallet using the string: walletprivatekey.new

**Comment by mrheinen** [comment]
Could you tell what generated the private key ? (Where the long name comes from?)

**Comment by Elektryon-Dev** [comment]
The online wallet generator generated the private key. The wallet works it just won`t save

**Comment by mrheinen** [comment]
Sorry but can you give me the command-line you use to do this ? Also the exact error message ?

**Comment by kebabman9001** [comment]
This issue is caused because of a misunderstanding of the commandline wallet.  The "arg" in the help is not the private key but the name of the wallet to create, if you put the private key as the arg it will try to create a wallet file named your private key and fail because the filename is too long.

The correct usage as specified on https://ombrewallet.com is:
```ombre-wallet-cli —generate-from-keys [WalletName]```

The wallet-cli will then prompt you to enter the keys.
